language: java
jdk:
    - openjdk7
env:
    global:
        - GLASSFISH_HOME=`pwd`/glassfish4
        - secure: "VKxO0XXnqGM6DWhDW7E5Bmt/Sz/IpzCY2FFeMQ3zrTlKwrwx2luEtUlGWdcU/0AFopfIwoel6eb0B34kPY4aLB+jW9Iw36NitJn+ND/E5TG+I09yEWw+3qhBjd2i3CyG/mVnIfSxpfBAXb6fMua6+qdJ5SzgrmvqqAaRvSFu4Lw="
before_install:
    # Glassfish
    - "wget -q http://dlc.sun.com.edgesuite.net/glassfish/4.1/release/glassfish-4.1.zip"
    - "unzip -qq glassfish-4.1.zip"
    - "rm glassfish-4.1.zip"
    - "cp -f ./domain.xml $GLASSFISH_HOME/glassfish/domains/domain1/config/domain.xml"
    - "wget -q http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-3.1.14.zip"
    - "unzip -qq mysql-connector-java-3.1.14.zip"
    - "rm mysql-connector-java-3.1.14.zip"
    - "cp -f ./mysql-connector-java-3.1.14/mysql-connector-java-3.1.14-bin.jar $GLASSFISH_HOME/glassfish/lib"
    # Update MySQL to 5.6
    - "wget -q http://repo.mysql.com/mysql-apt-config_0.2.1-1debian7_all.deb"
    - "sudo dpkg -i mysql-apt-config_0.2.1-1debian7_all.deb"
    - "sudo apt-get -qq update"
    - "yes Y | sudo apt-get -qq install mysql-server-5.6"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - mvn -q install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
    - mysql -e "CREATE DATABASE IF NOT EXISTS dac;" -uroot
    - mysql -e "CREATE USER 'dac'@'localhost' IDENTIFIED BY 'coucou';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'dac'@'localhost';" -uroot
    - mysql -e "FLUSH PRIVILEGES;" -uroot
    - mysql -udac -pcoucou -Ddac < ./sql/create.sql
    - mysql -udac -pcoucou -Ddac < ./sql/populate.sql
script:
    #EJB unit test
    - mvn -q test -DskipEjbTests=false
    #Webapp test (selenium)
    - $GLASSFISH_HOME/bin/asadmin start-domain
    - cd ./ear
    - mvn -q glassfish:deploy
    - cd ..
    - mvn -q test -DskipSeleniumTests=false
    - $GLASSFISH_HOME/bin/asadmin undeploy ear
    - $GLASSFISH_HOME/bin/asadmin stop-domain
after_success:
    - cd ./ejb
    - mvn -q clean compile exec:exec cobertura:cobertura coveralls:report -DskipEjbTests=false
