-- MySQL Script generated by MySQL Workbench
-- Thu Jan  8 16:31:40 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dac` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dac` ;

-- -----------------------------------------------------
-- Table `dac`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`User` ;

CREATE TABLE IF NOT EXISTS `dac`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(65,2) NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `banned` TINYINT(1) NOT NULL DEFAULT 0,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`Project` ;

CREATE TABLE IF NOT EXISTS `dac`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `idOwner` INT NOT NULL,
  `goal` DECIMAL(65,2) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(20000) NOT NULL,
  `creationDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endDate` DATETIME NOT NULL,
  `tags` VARCHAR(300) NOT NULL,
  `flagged` TINYINT(1) NOT NULL DEFAULT 0,
  `transferDone` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProject`),
  INDEX `idUser_idx` (`idOwner` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idOwner`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`Fund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`Fund` ;

CREATE TABLE IF NOT EXISTS `dac`.`Fund` (
  `idFund` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProject` INT NOT NULL,
  `value` DECIMAL(65,2) NOT NULL,
  INDEX `idProject_idx` (`idProject` ASC),
  PRIMARY KEY (`idFund`),
  CONSTRAINT `idUser_fund_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProject_fund_fk`
    FOREIGN KEY (`idProject`)
    REFERENCES `dac`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`Bonus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`Bonus` ;

CREATE TABLE IF NOT EXISTS `dac`.`Bonus` (
  `idBonus` INT NOT NULL AUTO_INCREMENT,
  `idProject` INT NOT NULL,
  `value` DECIMAL(65,2) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  INDEX `idProject_idx` (`idProject` ASC),
  PRIMARY KEY (`idBonus`),
  CONSTRAINT `idProject_bonus_fk`
    FOREIGN KEY (`idProject`)
    REFERENCES `dac`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`Comment` ;

CREATE TABLE IF NOT EXISTS `dac`.`Comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProject` INT NOT NULL,
  `comment` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idProject_idx` (`idProject` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  PRIMARY KEY (`idComment`),
  CONSTRAINT `idUser_comment_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProject_comment_fk`
    FOREIGN KEY (`idProject`)
    REFERENCES `dac`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`PrivateMessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`PrivateMessage` ;

CREATE TABLE IF NOT EXISTS `dac`.`PrivateMessage` (
  `idPrivateMessage` INT NOT NULL AUTO_INCREMENT,
  `exp` INT NOT NULL,
  `dest` INT NOT NULL,
  `message` VARCHAR(2000) NOT NULL,
  `isRead` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPrivateMessage`),
  INDEX `idUser_to_pm_fk_idx` (`dest` ASC),
  CONSTRAINT `idUser_from_pm_fk`
    FOREIGN KEY (`exp`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser_to_pm_fk`
    FOREIGN KEY (`dest`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`Notification` ;

CREATE TABLE IF NOT EXISTS `dac`.`Notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProject` INT NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isRead` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `idUser_idx` (`idUser` ASC),
  PRIMARY KEY (`idNotification`),
  INDEX `idProject_notif_fk_idx` (`idProject` ASC),
  CONSTRAINT `idUser_notif_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProject_notif_fk`
    FOREIGN KEY (`idProject`)
    REFERENCES `dac`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dac`.`MemoriseProject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac`.`MemoriseProject` ;

CREATE TABLE IF NOT EXISTS `dac`.`MemoriseProject` (
  `idMemoriseProject` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProject` INT NOT NULL,
  INDEX `idProject_idx` (`idProject` ASC),
  PRIMARY KEY (`idMemoriseProject`),
  UNIQUE INDEX `memorise_unique` (`idUser` ASC, `idProject` ASC),
  CONSTRAINT `idUser_memorise_fk`
    FOREIGN KEY (`idUser`)
    REFERENCES `dac`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProject_memorise_fk`
    FOREIGN KEY (`idProject`)
    REFERENCES `dac`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
